export { MapPinIcon } from './location/map-pin-icon';
export { AmericanIcon } from './payments/america-icon'
export { MasterCardIcon } from './payments/mastercard-icon'
export { OxxoIcon } from './payments/oxxo-icon'
export { PaypalIcon } from './payments/paypal-icon'
export { SpeiIcon } from './payments/spei-icon'
export { VisaIcon } from './payments/visa-icon';
export { CartCheckBagIcon } from './shop/cart-check-bag-icon';
export { CartIcon } from './shop/cart-icon';
export { CartOutlinedIcon } from './shop/cart-outlined-icon';
export { HeartFillIcon } from './shop/heart-fill-icon';
export { HeartOutlineIcon } from './shop/heart-outline-icon';
export { ShoppingBagIcon } from './shop/shopping-bag-icon';
export { FacebookIcon } from './social/facebook-icon'
export { GoogleIcon } from './social/google-icon';
export { InstagramIcon } from './social/instagram-icon'
export { TwitterIcon } from './social/twitter-icon'
export { YouTubeIcon } from './social/youtube-icon'
export { AnonymousIcon } from './ui/anonymous-icon';
export { LocationIcon } from './ui/location-icon';
export { ArrowDownIcon } from './ui/arrow-down-icon';
export { ArrowNextIcon } from './ui/arrow-next-icon';
export { ArrowPrevIcon } from './ui/arrow-prev-icon';
export { BackArrowRoundIcon } from './ui/back-arrow-round-icon';
export { CaretDownIcon } from './ui/caret-down-icon';
export { CheckIcon } from './ui/check-icon';
export { ChevronLeftIcon } from './ui/chevron-left-icon';
export { ChevronRightIcon } from './ui/chevron-right-icon';
export { CloseIcon } from './ui/close-icon';
export { ExpandLessIcon } from './ui/expand-less-icon';
export { ExpandMoreIcon } from './ui/expand-more-icon';
export { EyeIcon } from './ui/eye-icon';
export { EyeOffIcon } from './ui/eye-off-icon';
export { FilterIcon } from './ui/filter-icon';
export { HelpIcon } from './ui/help-icon';
export { HomeIcon } from './ui/home-icon';
export { InfoIcon } from './ui/info-icon';
export { MinusIcon } from './ui/minus-icon';
export { MobileIcon } from './ui/mobile-icon';
export { NavbarIcon } from './ui/navbar-icon';
export { PencilIcon } from './ui/pencil-icon';
export { PlusIcon } from './ui/plus-icon';
export { SadFaceIcon } from './ui/sad-face-icon';
export { SearchIcon } from './ui/search-icon';
export { SendIcon } from './ui/send-icon';
export { StarIcon } from './ui/star-icon';
export { TrashIcon } from './ui/trash-icon';
export { TruckIcon } from './ui/truck-icon'
export { UploadIcon } from './ui/upload-icon'
export { UserIcon } from './ui/user-icon'
export { UserOutlinedIcon } from './ui/user-outlined-icon'
